name: style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install mypy
    
  type annotation:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: mypy
      run: |
        mypy snippets/
  lint with flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  docstring coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: doccov
        run: |
          pip install doc-cov
          doccov snippets/ -fmc --output csv > doccov.csv
